### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by condensedapple**
just a small update

### CODE REVIEW

**Comment by p455w0rd** [comment]
I actually need this line translated to german as well:

You must first right-click with the Magnet Card in hand before using the keybind!

**Comment by condensedapple** [comment]
this would be: "Vor dem Benutzen des Tastenkürzels muss zuerst mit der Magnetkarte in der Hand ein Rechtsklick ausgeführt werden."

**Comment by p455w0rd** [comment]
Thank you! Instead of merging and since you're already on the contributors list, I'm going to just add these manually as it saves me from having to pull because I don't pull directory into my dev workspace. I use a separate folder for that. I'll also add you to the Credits list in README.md

**Comment by condensedapple** [comment]
Thanks a lot!

**Comment by p455w0rd** [comment]
what is your minecraft IGN?

**Comment by condensedapple** [comment]
42559248 (weird, i know)

**Comment by condensedapple** [comment]
just for information: I am using ur mod on my modded MC server, and my friends are very excited about it, too! The AE2-world with its addons is so awesome, forget 1.8.9/1.9.4 until AE2 + ExtraCells + WCT are updated.

**Comment by p455w0rd** [comment]
I've talked to thatsIch about ae2 1.8 and the main thing he needs is for someone to do the model work (which includes the code) for parts (terminals) & cables...I've contemplated it, and I'm definitely capable but I'm going to let that go a little while before I make an attempt at it because I have personal stuff I'm working on for 1.9. I did the same with this..I figured _someone_ would do it..but after so long I got tired of waiting and went ahead and made it

**Comment by p455w0rd** [comment]
do you use the default alex skin? i need your uuid..the uuid for 42559248 resolves to the alex skin

**Comment by condensedapple** [comment]
yes, I use the default one (since 2010 ;)

**Comment by p455w0rd** [comment]
oh ok :)
well get this version of WCT it has a fix for a feature I added for patrons: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.8b.jar have your friends use this version too so they can see =D

**Comment by p455w0rd** [comment]
heading out for a few hours..have fun

**Comment by condensedapple** [comment]
Thanks!!!
I wish you the best for your future modding, and a lot of motivation. Awesome work!

**Pull request closed without merging**
