### PR TITLE
Adding Italian Language to the mod

### PR DESCRIPTION
**Pull request by Davoleo**

### CODE REVIEW

**Comment by Davoleo** [comment]
So is this going to be merged?

**Comment by p455w0rd** [comment]
yes..after my next push, i'll merge this and pull :) - if i merge mid-push on my end, it'll screw things up

**Comment by Davoleo** [comment]
oki, thanks
I'll tag also the pulls on other mods you created
https://github.com/p455w0rd/EndermanEvolution/pull/25
https://github.com/p455w0rd/DankNull/pull/91

**Comment by Davoleo** [comment]
Just for a reminder :)

**Pull request merged**
