### PR TITLE
Adds Spanish Language & Adds configuration option for disabling crafting and mob drop of the booster card in any mode

### PR DESCRIPTION
**Pull request by TheCodedOne**

### CODE REVIEW

**Comment by TheCodedOne** [comment]
#15 Adds this feature

**Comment by p455w0rd** [comment]
I will look over this after I wake up a bit more..Looks like you have implemented the disabling of drops like I would have. But also, if possible, it would be really cool to have some light shed on #7 - I post on MC Forge forums and I'm not getting any feedback and I'm stumped. For more of an explanation see http://www.minecraftforge.net/forum/index.php/topic,38681.0.html - Thanks for contributing =D

**Comment by p455w0rd** [comment]
As far as changing WiFi to WAN..The description isn't meant to be literal. WiFi will stay

**Comment by p455w0rd** [comment]
To save me having to make 2 pushes to fix the changing of WAN back to WiFi, please change all occurrences of this. Looks good other than that. Once this change is made I'll accept the PR

**Comment by p455w0rd** [comment]
Well, I guess you have no interest in fixing this, so I'm going to close it.

**Comment by TheCodedOne** [comment]
Sorry was away for a few days, If you still want these changing and pushing i can do it.

**Comment by p455w0rd** [comment]
just need the translations..I'm getting ready to push another update right now though so give me about 30 mins

**Pull request closed without merging**
